services:
  gfpgan:
    build:
      context: .
    volumes:
      - /app/GFPGAN:/app
    ports:
      - 7890:8000
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
    restart: always
    command: "python3 main.py"